---
language: python
services: docker

env:
  global:
    - ROLE_NAME: jetbrains_installer
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora27

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME reimarstier.$ROLE_NAME
  - cd reimarstier.$ROLE_NAME

script:
  # Run tests.
  - molecule test
