---
- name: Download tool archive
  unarchive:
    src: "{{ jb_tool.download }}"
    dest: "{{ jetbrains_installer_dir }}/"
    remote_src: true
    list_files: true
  register: _archive_contents
  when: not _tool_exists.stat.exists

- name: Extract folder name from archive
  set_fact:
    extracted_folder: "{{ _archive_contents['files'][0].split('/')[0] }}"
  when: not _tool_exists.stat.exists

- name: Move extracted folder to destination
  command: >
    mv {{ jetbrains_installer_dir }}/{{ extracted_folder }}
       {{ jetbrains_installer_dir }}/{{ jb_tool.dirname }}
  args:
    creates: "{{ jetbrains_installer_dir }}/{{ jb_tool.dirname }}"
  when: not _tool_exists.stat.exists

- name: Create bin directory
  file:
    path: "{{ jetbrains_installer_dir }}/bin/"
    state: directory
  when: jb_tool.binary

- name: Create symlink for executable
  file:
    src: "{{ jetbrains_installer_dir }}/{{ jb_tool.dirname }}/bin/{{ jb_tool.binary }}"
    dest: "{{ jetbrains_installer_dir }}/bin/{{ jb_tool.link_name }}"
    state: "link"
  when: jb_tool.binary

- name: Create desktop file
  template:
    src: app.desktop
    dest: "/usr/share/applications/{{ jb_tool.link_name }}.desktop"
    mode: 0644
