---
- include_tasks: 00_pre_checks.yml

- name: Lookup jetbrains releases
  set_fact:
    jetbrains_releases: "{{ lookup('jetbrains_releases') }}"

- debug: msg="{{ jetbrains_releases }}"

- include_tasks: 10_select_tool.yml
  loop: "{{ jetbrains_installer_apps }}"
  loop_control:
    loop_var: tool_config
